{
 "title": "random Metric Visualization",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(abs(random_label - on (output_id) random_prediction) < 0.5) / count(random_label - on (output_id) random_prediction)"
    }
   ]
  },
  {
   "title": "Precision",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count( (random_label * on (output_id) random_prediction) > 0.5) / count((random_prediction and on (output_id) random_label) > 0.5)"
    }
   ]
  },
  {
   "title": "Recall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "count( (random_label * on (output_id) random_prediction) > 0.5) / count((random_label and on (output_id) random_prediction) == 1)"
    }
   ]
  }
 ]
}